# Numpy

==> NumPy is a general-purpose array-processing package. 

==> It provides a high-performance multidimensional array object, and tools for working with these arrays.

==> ‘ndarray’ object, aka ‘array’, you can store multiple items of the same data type. 

==> It is the facilities around the array object that makes numpy so convenient for performing math and data manipulations.

## Arrays

==> A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. 

==> The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [1]:
import numpy as np

In [2]:
# find out what is in our namespace
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [3]:
# Creating array object 
arr = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]] )

In [4]:
# Printing type of arr object 
print("Array is of type: ", type(arr)) 

Array is of type:  <class 'numpy.ndarray'>


In [5]:
# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 

No. of dimensions:  2


In [6]:
# Printing shape of array 
print("Shape of array: ", arr.shape) 

Shape of array:  (2, 3)


In [7]:
# Printing size (total number of elements) of array 
print("Size of array: ", arr.size)

Size of array:  6


In [8]:
# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype) 

Array stores elements of type:  int32


### Create Array

==> There are various ways to create arrays in NumPy.

==> **arange:** returns evenly spaced values within a given interval. step size is specified.

==> **linspace:** returns evenly spaced values within a given interval. num no. of elements are returned.

==> **For example:** np.zeros, np.ones, np.full, np.empty, etc.
To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.


In [9]:
# Creating array from list with type float 
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float') 
print ("Array created using passed list:\n", a) 

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [10]:
# Creating array from tuple 
b = np.array((1 , 3, 2)) 
print ("\nArray created using passed tuple:\n", b) 


Array created using passed tuple:
 [1 3 2]


In [11]:
# Creating a 3X4 array with all zeros 
c = np.zeros((3, 4)) 
print ("\nAn array initialized with all zeros:\n", c) 


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
arr = np.zeros((2,2))  # Create an array of all zeros
print(arr)

[[0. 0.]
 [0. 0.]]


In [13]:
arr = np.ones((1,2))   # Create an array of all ones
print(arr)

[[1. 1.]]


In [14]:
arr = np.full((2,2), 7) # Create a constant array
print(arr)

[[7 7]
 [7 7]]


In [15]:
arr1 = np.eye(2) # Create a 2x2 identity matrix
arr2 = np.eye(3) # Create a 3x3 identity matrix

print(arr1)
print(arr2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
arr = np.random.random((2,2)) # Create an array filled with random values
print(arr)

[[0.61967543 0.46215757]
 [0.46638262 0.94965677]]


In [17]:
#  Create a constant value array of complex type 
d = np.full((3, 3), 6, dtype = 'complex') 
print ("\nAn array initialized with all 6s." 
            "Array type is complex:\n", d) 


An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [18]:
# Create an array with random values 
e = np.random.random((2, 2)) 
print ("\nA random array:\n", e) 


A random array:
 [[0.49122918 0.75103926]
 [0.68514309 0.22027543]]


In [19]:
# Create a sequence of integers  
# from 0 to 30 with steps of 5 
f = np.arange(0, 30, 5) 
print ("\nA sequential array with steps of 5:\n", f) 


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [20]:
# Create a sequence of 10 values in range 0 to 5 
g = np.linspace(0, 5, 10) 
print ("\nA sequential array with 10 values between"
                                        "0 and 5:\n", g) 


A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [3]:
import numpy as np
# Reshaping 3X4 array to 2X2X3 array 
arr = np.array([[1, 2, 3, 4], 
                [5, 2, 4, 2], 
                [1, 2, 0, 1]])

In [5]:
newarr = arr.reshape(2, 2, 3) 

print ("\nOriginal array:\n", arr) 
print ("Reshaped array:\n", newarr) 


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [23]:
# Flatten array 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
flarr = arr.flatten() 
  
print ("\nOriginal array:\n", arr) 
print ("Fattened array:\n", flarr) 


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


#### More Example:

In [24]:
# create some uniform arrays
a = np.zeros((9,9))
print(a)
print("=========================================")
b = np.ones((3,6,3), dtype=np.complex128)
print(b)
print("=========================================")
c = np.full((3,3), np.pi)
print(c)
print("=========================================")
d = np.ones_like(c)
print(d)
print("=========================================")
e = np.zeros_like(d)
print(e)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[[1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]]

 [[1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]]

 [[1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]
  [1.+0.j 1.+0.j 1.+0.j]]]
[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# create some ranges
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# arange is left inclusive, right exclusive
np.arange(2,4,0.25)

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75])

In [27]:
# linearly spaced
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [28]:
# log spaced
np.logspace(1,2,10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [29]:
# two dimensional grids
x = np.linspace(-2*np.pi, 2*np.pi, 100)
y = np.linspace(-np.pi, np.pi, 50)
xx, yy = np.meshgrid(x, y)
xx.shape, yy.shape

((50, 100), (50, 100))

### Array indexing

==> Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multi-dimensional, you must specify a slice for each dimension of the array:

In [6]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1, 2, 3, 4]
#  [ 5, 6, 7, 8]
#  [ 9, 10, 11, 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
a[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [20]:
a[:,:]
# a[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a[1]

array([5, 6, 7, 8])

In [8]:
a[0]

array([1, 2, 3, 4])

In [9]:
a[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [10]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2, 3]
#  [6, 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


==> A slice of an array is a view into the same data, so modifying it will modify the original array.

In [21]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])
print(b)

2
77
[[77  3]
 [ 6  7]]


==> You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [36]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


==> Two ways of accessing the data in the middle row of the array. 

==> Mixing integer indexing with slices yields an array of lower rank, while using only slices yields an array of the same rank as the original array.

In [37]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [38]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


==> **Integer array indexing:** When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [39]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [40]:
# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [41]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


==> One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [42]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [43]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [44]:
print(a[np.arange(4)])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


==> **Boolean array indexing:** Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example

In [46]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [47]:
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


## Data Types

==> Every numpy array is a grid of elements of the same type. 

==> Numpy provides a large set of numeric datatypes that you can use to construct arrays. 

==> Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.

In [48]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


## Array math

In [22]:
x = np.array([[1,2], 
              [3,4]], dtype=np.float64)
y = np.array([[5,6], 
              [7,8]], dtype=np.float64)

# Element-wise sum; both produce the array
print(x + y)

[[ 6.  8.]
 [10. 12.]]


In [23]:
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


In [24]:
# Element-wise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [25]:
# Element-wise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [26]:
# Element-wise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [54]:
# Element-wise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [28]:
m = np.full((2,2),4)
m
print(np.sqrt(m))

[[2. 2.]
 [2. 2.]]


In [29]:
x = np.array([[1,2], [3,4]])
print(x)
print("===========================================")
y = np.array([[5,6], [7,8]])
print(y)
print("===========================================")
v = np.array([9,10])
print(v)
print("===========================================")
w = np.array([11,12])
print(w)
# w = w.T
# print(w)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 9 10]
[11 12]


In [56]:
# Inner product of vectors; both produce 219
print(v.dot(w))
print("===========================================")
print(np.dot(v, w))

219
219


In [57]:
# now make w as matrix then make dot product
w = np.array([[11,12]])
print(w)
print(np.dot(v, w))

[[11 12]]


ValueError: shapes (2,) and (1,2) not aligned: 2 (dim 0) != 1 (dim 0)

In [58]:
# Inner product of vectors; both produce 219
print(x.dot(y))
print("===========================================")
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [59]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print("===========================================")
print(np.dot(x, v))

[29 67]
[29 67]


==> Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [60]:
x = np.array([[1,2], [3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print("===========================================")
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print("===========================================")
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


==> Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [61]:
print(x)
print("===========================================")
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [62]:
v = np.array([[1,2,3]])

print(v) 
print("===========================================")
print(v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


==> When the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [63]:
v = np.array([1, 0, 1])
v

array([1, 0, 1])

In [64]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [65]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
y = x + vv  # Add x and vv element-wise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [67]:
w = np.array([4,5]) 

In [68]:
np.reshape(w, (2, 1))

array([[4],
       [5]])

In [69]:
np.reshape(x, (2, 2))

ValueError: cannot reshape array of size 12 into shape (2,2)

### More Example:

==> **Array Indexing:** Knowing the basics of array indexing is important for analysing and manipulating the array object. NumPy offers many ways to do array indexing.

==> **Slicing:** Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.

==> **Integer array indexing:** In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.

==> **Boolean array indexing:** This method is used when we want to pick elements from array which satisfy some condition.

In [70]:
# An exemple array 
arr = np.array([[-1, 2, 0, 4], 
[4, -0.5, 6, 0], 
[2.6, 0, 7, 8], 
[3, -7, 4, 2.0]]) 

# Slicing array 
temp = arr[:2, ::2] 
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp) 

# Integer array indexing example 
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]] 
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp) 

# boolean array indexing example 
cond = arr > 0 # cond is a boolean array 
temp = arr[cond] 
print ("\nElements greater than 0:\n", temp) 


Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


### Operations on single array:

==> We can use overloaded arithmetic operators to do element-wise operation on array to create a new array. In case of +=, -=, *= operators, the exsisting array is modified.

In [71]:
a = np.array([1, 2, 5, 3]) 

# add 1 to every element 
print ("Adding 1 to every element:", a+1) 
print("===============================================================")

# subtract 3 from each element 
print ("Subtracting 3 from each element:", a-3) 
print("===============================================================")

# multiply each element by 10 
print ("Multiplying each element by 10:", a*10) 
print("===============================================================")

# square each element 
print ("Squaring each element:", a**2) 
print("===============================================================")

# modify existing array 
a *= 2
print ("Doubled each element of original array:", a) 
print("===============================================================")

# transpose of array 
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]]) 

print ("\nOriginal array:\n", a) 
print("===============================================================")
print ("Transpose of array:\n", a.T) 


Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


### Unary operators

In [72]:
arr = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]]) 

# maximum element of array 
print ("Largest element is:", arr.max()) 
print("===============================================================")
print ("Row-wise maximum elements:",arr.max(axis = 1)) 
print("===============================================================")

# minimum element of array 
print ("Column-wise minimum elements:",arr.min(axis = 0)) 
print("===============================================================")

# sum of array elements 
print ("Sum of all array elements:",arr.sum()) 
print("===============================================================")

# cumulative sum along each row 
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1)) 


Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


### Binary operators

In [73]:
a = np.array([[1, 2], 
            [3, 4]]) 
b = np.array([[4, 3], 
            [2, 1]]) 

# add arrays 
print ("Array sum:\n", a + b) 
print("===============================================================")

# multiply arrays (elementwise multiplication) 
print ("Array multiplication:\n", a*b) 
print("===============================================================")

# matrix multiplication 
print ("Matrix multiplication:\n", a.dot(b)) 


Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


### Universal functions(Mathematics)

==> NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

In [74]:
# create an array of sine values 
a = np.array([0, np.pi/2, np.pi]) 
print ("Sine values of array elements:", np.sin(a)) 
print("=============================================================================")

# exponential values 
a = np.array([0, 1, 2, 3]) 
print ("Exponent of array elements:", np.exp(a)) 
print("=============================================================================")

# square root of array values 
print ("Square root of array elements:", np.sqrt(a)) 


Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


### Sorting array

In [75]:
a = np.array([[1, 4, 2], 
              [3, 4, 6], 
              [0, -1, 5]]) 

# sorted array 
print ("Array elements in sorted order:\n",np.sort(a, axis = None)) 
print("===============================================================")


# sort array row-wise 
print ("Row-wise sorted array:\n",np.sort(a, axis = 1)) 
print("===============================================================")

# specify sort algorithm 
print ("Column wise sort by applying merge-sort:\n",np.sort(a, axis = 0, kind = 'mergesort')) 
print("===============================================================")

# Example to show sorting of structured array 
# set alias names for dtypes 
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)] 

# Values to be put in array 
values = [('RK', 2009, 8.5), ('Abhay', 2008, 8.7),('Yana', 2008, 7.9), ('Riva', 2009, 9.0)]

# Creating array 
arr = np.array(values, dtype = dtypes) 
print ("\nArray sorted by names:\n",np.sort(arr, order = 'name')) 
print("===============================================================")

print ("Array sorted by grauation year and then cgpa:\n",np.sort(arr, order = ['grad_year', 'cgpa'])) 


Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Abhay', 2008, 8.7) (b'RK', 2009, 8.5) (b'Riva', 2009, 9. )
 (b'Yana', 2008, 7.9)]
Array sorted by grauation year and then cgpa:
 [(b'Yana', 2008, 7.9) (b'Abhay', 2008, 8.7) (b'RK', 2009, 8.5)
 (b'Riva', 2009, 9. )]


### numpy.ndarray.__pos__()

==> **numpy.ndarray.__pos__()** method of Numpy, one can multiply each and every element of an array with 1. Hence, the resultant array having values same as original array.

In [76]:
# make an array with numpy 
RK = np.array([1, -2, 3, 4, 5, 6]) 

# applying numpy.__pos__() method 
print(RK.__pos__()) 

[ 1 -2  3  4  5  6]


In [77]:
# make an array with numpy 
RK = np.array([[1, 2, -3, 4, 5, 6],
                [-6, 5, 4, 3, 2, -1]]) 

# applying numpy.__pos__() method 
print(RK.__pos__()) 

[[ 1  2 -3  4  5  6]
 [-6  5  4  3  2 -1]]


### numpy.ndarray.__imul__()

==> **numpy.ndarray.__imul__()** method, we can multiply a particular value that is provided as a parameter in the ndarray.__imul__() method. Value will be multiplied to every element in a numpy array.

In [78]:
# make an array with numpy 
RK = np.array([1.2, 2.6, 3, 4.5, 5]) 

# applying ndarray.__imul__() method 
print(RK.__imul__(5)) 

[ 6.  13.  15.  22.5 25. ]


In [79]:
# make an array with numpy 
RK = np.array([[1, 2.2, 3, 4, 5.01], 
                [6.1, 5, 4.8, 3, 2]]) 
    
# applying ndarray.__imul__() method 
print(RK.__imul__(3)) 

[[ 3.    6.6   9.   12.   15.03]
 [18.3  15.   14.4   9.    6.  ]]


### numpy.ndarray.__isub__()

==> **numpy.ndarray.__isub__()** method, we can subtract a particular value that is provided as a parameter in the **ndarray.__isub__()** method. Value will be subtracted to every element in a numpy array.

In [80]:
# make an array with numpy 
RK = np.array([1.2, 2.6, 3, 4.5, 5]) 
    
# applying ndarray.__isub__() method 
print(RK.__isub__(5)) 

[-3.8 -2.4 -2.  -0.5  0. ]


In [81]:
# make an array with numpy 
RK = np.array([[1, 2.2, 3, 4, 5.01], 
                [6.1, 5, 4.8, 3, 2]]) 
    
# applying ndarray.__isub__() method 
print(RK.__isub__(3)) 

[[-2.   -0.8   0.    1.    2.01]
 [ 3.1   2.    1.8   0.   -1.  ]]


### numpy.ndarray.__and__()

==> **numpy.ndarray.__and__()** method, we can get the elements that is anded by the value that is provided as a parameter in **numpy.ndarray.__and__()** method.

In [82]:
# make an array with numpy 
RK = np.array([1, 2, 3, 4, 5]) 
     
# applying ndarray.__and__() method 
print(RK.__and__(2))

[0 2 2 0 0]


In [83]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4, 5], 
                [6, 5, 4, 3, 2]]) 
     
# applying ndarray.__and__() method 
print(RK.__and__(1)) 

[[1 0 1 0 1]
 [0 1 0 1 0]]


### numpy.ndarray.__or__()

==> Numpy **numpy.ndarray.__or__()** method, we can get the elements that is OR by the value that is provided as a parameter in numpy.ndarray.__or__() method.

==> we can see that every element is or by the value that is passed as a parameter in **ndarray.__or__()** method.

In [84]:
import numpy as np 

# make an array with numpy 
RK = np.array([1, 2, 3, 4, 5]) 

# applying ndarray.__or__() method 
print(RK.__or__(2)) 

[3 2 3 6 7]


In [85]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4, 5], 
                [6, 5, 4, 3, 2]]) 
     
# applying ndarray.__or__() method 
print(RK.__or__(1)) 

[[1 3 3 5 5]
 [7 5 5 3 3]]


### numpy.ndarray.__pow__()

==> Numpy **numpy.ndarray.__pow__()** method, we will get all the elements powered with the value that is provided as a parameter in **numpy.ndarray.__pow__()** method.

==> we can see that every element get powered with the value that is provided as a parameter in **ndarray.__pow__()** method.

In [86]:
# make an array with numpy 
RK = np.array([1, 2, 3, 4, 5]) 
     
# applying ndarray.__pow__() method 
print(RK.__pow__(3)) 

[  1   8  27  64 125]


In [87]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4, 5], 
                [6, 5, 4, 3, 2]]) 
     
# applying ndarray.__pow__() method 
print(RK.__pow__(2)) 

[[ 1  4  9 16 25]
 [36 25 16  9  4]]


### numpy.ndarray.__neg__()

==> **numpy.ndarray.__neg__()** method of Numpy, one can multiply each and every element of an array with **-1**. Hence, the resultant array having values like positive values becomes negative and negative values become positive.

==> we can see that after applying **numpy.__neg__()**, we get the simple array with combination of positive and negative values in an array.

In [88]:
# make an array with numpy 
RK = np.array([1, -2, 3, 4, 5, 6]) 
  
# applying numpy.__neg__() method 
print(RK.__neg__()) 

[-1  2 -3 -4 -5 -6]


In [89]:
# make an array with numpy 
RK = np.array([[1, 2, -3, 4, 5, 6], 
                [-6, 5, 4, 3, 2, -1]]) 
  
# applying numpy.__neg__() method 
print(RK.__neg__()) 

[[-1 -2  3 -4 -5 -6]
 [ 6 -5 -4 -3 -2  1]]


### numpy.ndarray.__truediv__()

==> Numpy **numpy.ndarray.__truediv__()**, we can divide a particular value that is provided as a parameter in the **ndarray.__truediv__()** method. Value will be divided to each and every element in a numpy array.

==> we can see that each element in an array is divided with the value given as a parameter in method ndarray.__truediv__(). This method will work fine for positive, negative and floating point values of an array.

In [90]:
# make an array with numpy 
RK = np.array([1, 2.5, 3, 4.8, 5]) 
   
# applying ndarray.__truediv__() method 
print(RK.__truediv__(2)) 

[0.5  1.25 1.5  2.4  2.5 ]


In [91]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4.45, 5], 
                [6, 5.5, 4, 3, 2.62]]) 
   
# applying ndarray.__truediv__() method 
print(RK.__truediv__(3)) 

[[0.33333333 0.66666667 1.         1.48333333 1.66666667]
 [2.         1.83333333 1.33333333 1.         0.87333333]]


### numpy.ndarray.__mul__()

==> Numpy **numpy.ndarray.__mul__()**, we can multiply a particular value that is provided as a parameter in the **ndarray.__mul__()** method. Value will be multiplied to each and every element in a numpy array.

==> we can see that each element in an array is multiplied with the value given as a parameter in method **ndarray.__mul__()**. This method will work fine for positive, negative and floating point values of an array.

In [92]:
# make an array with numpy 
RK = np.array([1, 2.5, 3, 4.8, 5]) 
   
# applying ndarray.__mul__() method 
print(RK.__mul__(5)) 

[ 5.  12.5 15.  24.  25. ]


In [93]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4.45, 5], 
                [6, 5.5, 4, 3, 2.62]]) 
   
# applying ndarray.__mul__() method 
print(RK.__mul__(5)) 

[[ 5.   10.   15.   22.25 25.  ]
 [30.   27.5  20.   15.   13.1 ]]


### numpy.ndarray.__sub__()

==> Numpy **numpy.ndarray.__sub__()**, We can subtract a particular value that is provided as a parameter in the **ndarray.__sub__()** method. Value will be subtracted to each and every element in a numpy array.

==> we can see that each and every element in an array is subtracted with the value given as a parameter in method **ndarray.__sub__()**. Remember one thing it wouldn’t work for double type values.

In [94]:
# make an array with numpy 
RK = np.array([1, 2, 3, 4, 5]) 
   
# applying ndarray.__sub__() method 
print(RK.__sub__(5)) 

[-4 -3 -2 -1  0]


In [95]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4, 5], 
                [6, 5, 4, 3, 2]]) 
   
# applying ndarray.__sub__() method 
print(RK.__sub__(5)) 

[[-4 -3 -2 -1  0]
 [ 1  0 -1 -2 -3]]


### numpy.ndarray.__ne__()

==> **numpy.ndarray.__ne__()** method of Numpy, We can find that which element in an array is not equal to the value which is provided in the parameter. It will return you numpy array with boolean type having only values True and False.

==> we can see that after applying **numpy.__ne__()**, we get the simple boolean array that can tell us which element in an array is not equal to that of provided parameter.

In [96]:
# make an array with numpy 
RK = np.array([1, 2, 3, 4, 5, 6]) 
  
# applying numpy.__ne__() method 
print(RK.__ne__(4)) 

[ True  True  True False  True  True]


In [97]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4, 5, 6], 
                [6, 5, 4, 3, 2, 1]]) 
  
# applying numpy.__ne__() method 
print(RK.__ne__(4)) 

[[ True  True  True False  True  True]
 [ True  True False  True  True  True]]


### numpy.ndarray.__invert__()

==> Numpy **numpy.ndarray.__invert__()**, one can invert the elements of an array. We don’t have to provide any type of parameter but remember that this method only works for integer values.

==> we can see that every element in an array is operated on a unary operator that is ~ with the help of **ndarray.__invert__()** method.

In [98]:
# make an array with numpy 
RK = np.array([1, 2, 3, 4, 5]) 
    
# applying ndarray.__invert__() method 
print(RK.__invert__())

[-2 -3 -4 -5 -6]


In [99]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4, 5], 
                [6, 5, 4, 3, 2]]) 
    
# applying ndarray.__invert__() method 
print(RK.__invert__()) 

[[-2 -3 -4 -5 -6]
 [-7 -6 -5 -4 -3]]


### numpy.ndarray.__lt__()

==> **numpy.ndarray.__lt__()** method of Numpy, We can find that which element in an array is less then the value which is provided in the parameter. It will return you numpy array with boolean type having only values True and False.

==> we can see that after applying **numpy.__lt__()**, we get the simple boolean array that can tell us which element in an array is less then that of provided parameter.

In [100]:
# make an array with numpy 
RK = np.array([1, 2, 3, 4, 5, 6]) 
  
# applying numpy.__lt__() method 
print(RK.__lt__(4)) 

[ True  True  True False False False]


In [101]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4, 5, 6], 
                [6, 5, 4, 3, 2, 1]]) 
  
# applying numpy.__lt__() method 
print(RK.__lt__(4)) 

[[ True  True  True False False False]
 [False False False  True  True  True]]


### numpy.ndarray.__gt__()

==> **numpy.ndarray.__gt__()** method of Numpy, We can find that which element in an array is greater then the value which is provided in the parameter. It will return you numpy array with boolean type having only values True and False.

==> we can see that after applying **numpy.__gt__()**, we get the simple boolean array that can tell us which element in an array is greater than that of provided parameter.

In [102]:
# make an array with numpy 
RK = np.array([1, 2, 3, 4, 5, 6]) 
  
# applying numpy.__gt__() method 
print(RK.__gt__(3)) 

[False False False  True  True  True]


In [103]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4, 5, 6], 
                [6, 5, 4, 3, 2, 1]]) 
  
# applying numpy.__gt__() method 
print(RK.__gt__(4)) 

[[False False False False  True  True]
 [ True  True False False False False]]


### numpy.ndarray.__le__()

==> **numpy.ndarray.__le__()** method of Numpy, We can find that which element in an array is less then or equal to the value which is provided in the parameter. It will return you numpy array with boolean type having only values True and False.

==> we can see that after applying **numpy.__le__()**, we get the simple boolean array that can tell us which element in an array is less than or equal to that of provided parameter.

In [104]:
# make an array with numpy 
RK = np.array([1, 2, 3, 4, 5, 6]) 
  
# applying numpy.__le__() method 
print(RK.__le__(4)) 

[ True  True  True  True False False]


In [105]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4, 5, 6], 
                [6, 5, 4, 3, 2, 1]]) 
  
# applying numpy.__le__() method 
print(RK.__le__(4)) 

[[ True  True  True  True False False]
 [False False  True  True  True  True]]


### numpy.ndarray.__ge__()

==> **numpy.ndarray.__ge__()** method of Numpy, We can find that which element in an array is greater then or equal to the value which is provided in the parameter. It will return you numpy array with boolean type having only values True and False.

==> we can see that after applying **numpy.__ge__()**, we get the simple boolean array that can tell us which element in an array is greater then or equal to that of provided parameter.

In [106]:
# make an array with numpy 
RK = np.array([1, 2, 3, 4, 5, 6]) 
  
# applying numpy.__ge__() method 
print(RK.__ge__(4)) 

[False False False  True  True  True]


In [107]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4, 5, 6], 
                [6, 5, 4, 3, 2, 1]]) 
  
# applying numpy.__ge__() method 
print(RK.__ge__(4))

[[False False False  True  True  True]
 [ True  True  True False False False]]


### numpy.ndarray.__eq__()

==> **numpy.ndarray.__eq__()** method of Numpy, We can find that which element in an array is equal to the value which is provided in the parameter. It will return you numpy array with boolean type having only values True and False.

==> we can see that after applying **numpy.__eq__()**, we get the simple boolean array that can tell us which element in an array is equal to that of provided parameter.

In [108]:
# make an array with numpy 
RK = np.array([1, 2, 3, 4, 5, 6]) 
  
# applying numpy.__eq__() method 
print(RK.__eq__(4)) 

[False False False  True False False]


In [109]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4, 5, 6], 
                [6, 5, 4, 3, 2, 1]]) 
  
# applying numpy.__eq__() method 
print(RK.__eq__(4)) 

[[False False False  True False False]
 [False False  True False False False]]


### numpy.ndarray.__add__()

==>  Numpy **numpy.ndarray.__add__()**, we can add a particular value that is provided as a parameter in the **ndarray.__add__()** method. Value will be added to each and every element in a numpy array.

==> we can see that each and every element in an array is added with the value given as a parameter in method **ndarray.__add__()**. Remember one thing it wouldn’t work for double type values.

In [110]:
# make an array with numpy 
RK = np.array([1, 2, 3, 4, 5]) 
   
# applying ndarray.__add__() method 
print(RK.__add__(5)) 

[ 6  7  8  9 10]


In [111]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4, 5], 
                [6, 5, 4, 3, 2]]) 
   
# applying ndarray.__add__() method 
print(RK.__add__(5))

[[ 6  7  8  9 10]
 [11 10  9  8  7]]


### numpy.ndarray.__iadd__()

==> **numpy.ndarray.__iadd__()** method, we can add a particular value that is provided as a parameter in the **ndarray.__iadd__()** method. Value will be added to every element in a numpy array.

==> we can see that each and every element in an array is added with the value given as a parameter in method **ndarray.__iadd__()**. Remember this method will work with every type of numeric value.

In [112]:
# make an array with numpy 
RK = np.array([1.2, 2.6, 3, 4.5, 5]) 
    
# applying ndarray.__iadd__() method 
print(RK.__iadd__(5)) 

[ 6.2  7.6  8.   9.5 10. ]


In [113]:
# make an array with numpy 
RK = np.array([[1, 2.2, 3, 4, 5.01], 
                [6.1, 5, 4.8, 3, 2]]) 
    
# applying ndarray.__iadd__() method 
print(RK.__iadd__(3)) 

[[4.   5.2  6.   7.   8.01]
 [9.1  8.   7.8  6.   5.  ]]


### numpy.ndarray.__xor__()

==> Numpy **numpy.ndarray.__xor__()** method, we can get the elements that is XOR by the value that is provided as a parameter in **numpy.ndarray.__xor__()** method.

==> we can see that every element is xor by the value that is passed as a parameter in **ndarray.__xor__()** method.

In [114]:
# make an array with numpy 
RK = np.array([1, 2, 3, 4, 5]) 
     
# applying ndarray.__xor__() method 
print(RK.__xor__(2)) 

[3 0 1 6 7]


In [115]:
# make an array with numpy 
RK = np.array([[1, 2, 3, 4, 5], 
                [6, 5, 4, 3, 2]]) 
     
# applying ndarray.__xor__() method 
print(RK.__xor__(1)) 

[[0 3 2 5 4]
 [7 4 5 2 3]]


#### RAJKUMAR ZALAVADIA - Mo: 7041645834 Email : rajzalavadia50@gmail.com